const http = require('http');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const port = Number(process.env.PORT || 3000);
const root = path.join(__dirname, 'public');
const dataDir = path.join(__dirname, 'data');
const usersPath = path.join(dataDir, 'users.json');
const sessions = new Map();
fs.mkdirSync(dataDir, { recursive: true });
if (!fs.existsSync(usersPath)) fs.writeFileSync(usersPath, '[]', { mode: 0o600 });
const users = () => JSON.parse(fs.readFileSync(usersPath, 'utf8'));
const saveUsers = value => fs.writeFileSync(usersPath, JSON.stringify(value, null, 2), { mode: 0o600 });
const hash = (password, salt = crypto.randomBytes(16).toString('hex')) => ({ salt, hash: crypto.scryptSync(password, salt, 64).toString('hex') });
const json = (res, status, body, headers = {}) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', ...headers }); res.end(JSON.stringify(body)); };
const readBody = req => new Promise((resolve, reject) => { let raw = ''; req.on('data', d => raw += d); req.on('end', () => { try { resolve(JSON.parse(raw || '{}')); } catch { reject(Error('Invalid request')); } }); });
const session = req => { const match = (req.headers.cookie || '').match(/sp_session=([^;]+)/); return match && sessions.get(match[1]); };
function beginSession(res, user) { const id = crypto.randomBytes(32).toString('base64url'); sessions.set(id, { email: user.email }); res.setHeader('Set-Cookie', 'sp_session=' + id + '; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800'); }
async function weather(url, res) { const place = (url.searchParams.get('place') || '').trim(), date = url.searchParams.get('date'); const geo = await fetch('https://geocoding-api.open-meteo.com/v1/search?name=' + encodeURIComponent(place) + '&count=20&language=en&format=json'); const location = ((await geo.json()).results || []).find(x => x.country_code === 'IN'); if (!location) return json(res, 404, { error: 'No Indian district or town matched that search.' }); const params = new URLSearchParams({ latitude: location.latitude, longitude: location.longitude, timezone: 'Asia/Kolkata', start_date: date, end_date: date, hourly: 'temperature_2m,relative_humidity_2m,precipitation_probability,weather_code,wind_speed_10m' }); const data = await (await fetch('https://api.open-meteo.com/v1/forecast?' + params)).json(); json(res, 200, { location: { name: location.name, state: location.admin1 || '' }, hourly: data.hourly }); }
const server = http.createServer(async (req, res) => { const url = new URL(req.url, 'http://' + req.headers.host); try { if (req.method === 'POST' && ['/api/auth/signup','/api/auth/signin'].includes(url.pathname)) { const { email = '', password = '' } = await readBody(req), normalized = email.trim().toLowerCase(); if (!/^S+@S+.S+$/.test(normalized) || password.length < 8) return json(res, 400, { error: 'Use a valid email and a password of at least 8 characters.' }); const list = users(); let user = list.find(x => x.email === normalized); if (url.pathname.endsWith('signup')) { if (user) return json(res, 409, { error: 'An account already exists for this email.' }); user = { email: normalized, ...hash(password) }; list.push(user); saveUsers(list); } else if (!user || crypto.scryptSync(password, user.salt, 64).toString('hex') !== user.hash) return json(res, 401, { error: 'Email or password is incorrect.' }); beginSession(res, user); return json(res, 200, { email: user.email }); } if (req.method === 'POST' && url.pathname === '/api/auth/logout') return json(res, 200, { ok: true }, { 'Set-Cookie': 'sp_session=; Path=/; Max-Age=0' }); if (url.pathname === '/api/weather') { if (!session(req)) return json(res, 401, { error: 'Please sign in.' }); return await weather(url, res); } if (url.pathname === '/api/auth/me') return session(req) ? json(res, 200, session(req)) : json(res, 401, { error: 'Not signed in' }); const file = url.pathname === '/' ? 'index.html' : url.pathname.slice(1), resolved = path.resolve(root, file); if (!resolved.startsWith(root) || !fs.existsSync(resolved)) return json(res, 404, { error: 'Not found' }); res.writeHead(200, { 'content-type': file.endsWith('.js') ? 'text/javascript' : 'text/html; charset=utf-8' }); fs.createReadStream(resolved).pipe(res); } catch (error) { console.error(error); json(res, 500, { error: 'Server error' }); } });
server.listen(port, () => console.log('Sky Predict running on port ' + port));
